/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.InlineResponse200;
import io.swagger.model.InlineResponse20020;
import io.swagger.model.InlineResponse20021;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-03T13:27:38.359Z")

@Api(value = "chapter", description = "the chapter API")
public interface ChapterApi {

    @ApiOperation(value = "购买章节", nickname = "chapterbuy", notes = "购买章节", response = InlineResponse200.class, tags={ "Chapter", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "章节详情", response = InlineResponse200.class),
        @ApiResponse(code = 200, message = "error", response = Error.class) })
    @RequestMapping(value = "/chapter/buy",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse200> chapterbuy(@ApiParam(value = "当前后台登录id") @Valid @RequestParam(value = "userid", required = false) Long userid,@ApiParam(value = "章节id") @Valid @RequestParam(value = "chapterId", required = false) String chapterId);


    @ApiOperation(value = "章节详情", nickname = "chapterdetail", notes = "章节详情", response = InlineResponse20021.class, tags={ "Chapter", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "章节详情", response = InlineResponse20021.class),
        @ApiResponse(code = 200, message = "error", response = Error.class) })
    @RequestMapping(value = "/chapter/detail",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse20021> chapterdetail(@ApiParam(value = "当前后台登录id") @Valid @RequestParam(value = "userid", required = false) Long userid,@ApiParam(value = "章节id") @Valid @RequestParam(value = "chapterId", required = false) String chapterId);


    @ApiOperation(value = "收藏/取消收藏章节", nickname = "chapterfav", notes = "收藏/取消收藏章节", response = InlineResponse200.class, tags={ "Chapter", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "章节详情", response = InlineResponse200.class),
        @ApiResponse(code = 200, message = "error", response = Error.class) })
    @RequestMapping(value = "/chapter/fav",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse200> chapterfav(@ApiParam(value = "当前后台登录id") @Valid @RequestParam(value = "userid", required = false) Long userid,@ApiParam(value = "章节id") @Valid @RequestParam(value = "chapterId", required = false) String chapterId,@ApiParam(value = "fav/unfav") @Valid @RequestParam(value = "action", required = false) String action);


    @ApiOperation(value = "用户收藏的书的章节列表", nickname = "chapterfavlist", notes = "获取我收藏的章节列表", response = InlineResponse20020.class, tags={ "Chapter", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "登录成功，返回登录信息", response = InlineResponse20020.class),
        @ApiResponse(code = 200, message = "error", response = Error.class) })
    @RequestMapping(value = "/chapter/list/fav",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse20020> chapterfavlist(@ApiParam(value = "开始时间戳") @Valid @RequestParam(value = "startTs", required = false) Long startTs,@ApiParam(value = "结束时间戳") @Valid @RequestParam(value = "endTs", required = false) Long endTs,@ApiParam(value = "标签(如:文学|历史|卡通)") @Valid @RequestParam(value = "tags", required = false) String tags,@ApiParam(value = "年级(如:1-4)") @Valid @RequestParam(value = "grade", required = false) String grade,@ApiParam(value = "版本号") @Valid @RequestParam(value = "version", required = false) String version,@ApiParam(value = "唯一识别号") @Valid @RequestParam(value = "imei", required = false) String imei,@ApiParam(value = "客户端类型") @Valid @RequestParam(value = "client", required = false) String client,@ApiParam(value = "用户id") @Valid @RequestParam(value = "memberId", required = false) String memberId,@ApiParam(value = "分页索引") @Valid @RequestParam(value = "pageIndex", required = false) Long pageIndex,@ApiParam(value = "分页尺寸") @Valid @RequestParam(value = "pageSize", required = false) Long pageSize);


    @ApiOperation(value = "书的章节列表", nickname = "chapterhistorylist", notes = "浏览历史记录", response = InlineResponse20020.class, tags={ "Chapter", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "登录成功，返回登录信息", response = InlineResponse20020.class),
        @ApiResponse(code = 200, message = "error", response = Error.class) })
    @RequestMapping(value = "/chapter/list/history",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<InlineResponse20020> chapterhistorylist(@ApiParam(value = "开始时间戳") @Valid @RequestParam(value = "startTs", required = false) Long startTs,@ApiParam(value = "结束时间戳") @Valid @RequestParam(value = "endTs", required = false) Long endTs,@ApiParam(value = "标签(如:文学|历史|卡通)") @Valid @RequestParam(value = "tags", required = false) String tags,@ApiParam(value = "年级(如:1-4)") @Valid @RequestParam(value = "grade", required = false) String grade,@ApiParam(value = "版本号") @Valid @RequestParam(value = "version", required = false) String version,@ApiParam(value = "唯一识别号") @Valid @RequestParam(value = "imei", required = false) String imei,@ApiParam(value = "客户端类型") @Valid @RequestParam(value = "client", required = false) String client,@ApiParam(value = "用户id") @Valid @RequestParam(value = "memberId", required = false) String memberId,@ApiParam(value = "分页索引") @Valid @RequestParam(value = "pageIndex", required = false) Long pageIndex,@ApiParam(value = "分页尺寸") @Valid @RequestParam(value = "pageSize", required = false) Long pageSize);

}
